name: CI
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        with:
          environment-file: environment.yaml
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          pip install .
          pytest tests
